version: '3.9'

services:
  django:
    image: django-docker:0.01
    build: .
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate && 
                    python manage.py runserver 127.0.0.1:8000"
    ports:
      - "8000:8000"
